### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by sambody** [kenspirit/MarkdownCodeBlockWrapper#1]
I was trying it out by using the command shortcut, then typing "markdowncode...", but that didn't work. It's only after looking at the source code that I understood that I had to type "**mdcode**...". You may want to clarify this in your readme file, to make it more explicit. (or just change it to markdowncode, as Sublime Text will pick it up too when typing mdcode...).

**Comment by kenspirit** [comment]
Thanks very much for using this tool and suggestion.
